/**
 * Discovering and installing extensions from a published registry.
 *
 * The registry is metadata: ids, versions, licence identifiers and — when it
 * was generated by a release — the URLs and sha256 of built artefacts. No code
 * crosses this boundary until the user asks for a specific extension, and even
 * then the ordinary install trust prompt still runs.
 *
 * WHY THE RENDERER ONLY EVER PASSES AN ID. An earlier shape let the caller hand
 * in a URL. That turns the main process into a general-purpose fetcher for
 * whatever the renderer asks for. Here the renderer names an extension, and
 * main resolves the URL itself from the registry it fetched, so a compromised
 * renderer cannot choose what gets downloaded.
 *
 * WHY THE DEFAULT IS A PRODUCT ADDRESS. The registry lives in a repository
 * published from a separate account. Hardcoding that account here would put its
 * name in Natively's source and inside every shipped app.asar, which anyone can
 * extract. A natively.software address keeps the account out of the binary —
 * though a redirect only obscures a destination, it does not hide one.
 */

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { fetchRemoteRegistry, stageFromDirectory, type RegistryEntry } from './ExtensionInstaller';
import { downloadExtensionPayload, type DownloadOptions } from './ExtensionPayloadDownloader';

/**
 * Natively's own API, which PROXIES the registry rather than redirecting to it.
 *
 * A redirect would put the upstream URL in the Location header, so every client
 * would learn where the registry is published — which defeats the point of not
 * naming it in this binary. The proxy also gives one warm cache for everyone
 * and keeps serving a stale copy when the upstream is briefly unreachable.
 *
 * The marketing site was the first choice, but it answers every path with the
 * SPA shell: `/extensions/registry.json` returned 200 with `text/html`, which
 * fails at JSON.parse rather than failing honestly.
 */
export const DEFAULT_REGISTRY_URL = 'https://api.natively.software/v1/extensions/registry.json';

/** How long a fetched registry is reused before going back to the network. */
export const REGISTRY_CACHE_TTL_MS = 15 * 60 * 1000;

export interface RegistrySnapshot {
  ok: boolean;
  entries: RegistryEntry[];
  /** True when these entries came from cache rather than the network. */
  cached: boolean;
  fetchedAt: number;
  error?: string;
}

let cache: { url: string; snapshot: RegistrySnapshot } | null = null;

/** Explicit argument wins, then the env override, then the product address. */
export function resolveRegistryUrl(requested?: string): { ok: true; url: string } | { ok: false; error: string } {
  const candidate = (requested || process.env.NATIVELY_EXTENSION_REGISTRY_URL || DEFAULT_REGISTRY_URL).trim();
  try {
    const parsed = new URL(candidate);
    // https only: a renderer-supplied string must not become a file:// read or
    // a request to a loopback service.
    if (parsed.protocol !== 'https:') return { ok: false, error: 'registry_must_be_https' };
    return { ok: true, url: parsed.toString() };
  } catch {
    return { ok: false, error: 'invalid_registry_url' };
  }
}

export interface BrowseOptions {
  url?: string;
  force?: boolean;
  fetchImpl?: typeof fetch;
  now?: () => number;
}

/**
 * Fetch the registry, reusing a recent result.
 *
 * On a network failure with a cached snapshot available, the cache is returned
 * rather than an empty list: a transient outage should not make an installed
 * catalogue appear to vanish. Opening Settings must never block on this.
 */
export async function browseRegistry(options: BrowseOptions = {}): Promise<RegistrySnapshot> {
  const now = options.now ?? Date.now;
  const resolved = resolveRegistryUrl(options.url);
  if (!resolved.ok) return { ok: false, entries: [], cached: false, fetchedAt: now(), error: resolved.error };

  const fresh = cache
    && cache.url === resolved.url
    && now() - cache.snapshot.fetchedAt < REGISTRY_CACHE_TTL_MS;
  if (fresh && !options.force) return { ...cache!.snapshot, cached: true };

  const result = await fetchRemoteRegistry(resolved.url, options.fetchImpl ?? fetch);
  if (!result.ok) {
    if (cache && cache.url === resolved.url) {
      // Offline, but we have seen this registry before.
      return { ...cache.snapshot, cached: true, error: 'registry_unreachable' };
    }
    return { ok: false, entries: [], cached: false, fetchedAt: now(), error: 'registry_unreachable' };
  }

  const snapshot: RegistrySnapshot = { ok: true, entries: result.entries, cached: false, fetchedAt: now() };
  cache = { url: resolved.url, snapshot };
  return snapshot;
}

/** Tests, and anywhere that must not see a previous run's registry. */
export function clearRegistryCache(): void {
  cache = null;
}

export type RegistryInstallResult =
  | { ok: true; id: string; payloadDir: string; manifestJson: unknown; warnings: string[] }
  | { ok: false; error: string; errors?: string[] };

export interface RegistryInstallOptions extends BrowseOptions {
  download?: DownloadOptions;
  /** Staging root. Defaults to a fresh temp directory. */
  stagingDir?: string;
}

/**
 * Resolve an id against the registry, download its artefacts, and stage them.
 *
 * Returns a staged payload; it does NOT install. The caller passes the result
 * to `ExtensionManager.install`, which runs the trust prompt. Keeping those
 * separate is deliberate: nothing here can bypass consent.
 */
export async function stageFromRegistry(
  id: string,
  options: RegistryInstallOptions = {},
): Promise<RegistryInstallResult> {
  if (typeof id !== 'string' || !id.trim()) return { ok: false, error: 'invalid_id' };

  const snapshot = await browseRegistry(options);
  if (!snapshot.ok && snapshot.entries.length === 0) {
    return { ok: false, error: snapshot.error ?? 'registry_unreachable' };
  }

  const entry = snapshot.entries.find((e) => e.id === id);
  if (!entry) return { ok: false, error: 'not_in_registry' };
  if (!entry.download) {
    // Discoverable but not installable in-app: the registry carries no built
    // artefacts for it. Say so rather than failing obscurely.
    return { ok: false, error: 'no_published_build' };
  }

  const stagingDir = options.stagingDir
    ?? fs.mkdtempSync(path.join(os.tmpdir(), `natively-ext-${id}-`));
  fs.mkdirSync(stagingDir, { recursive: true });

  // Thread the caller's fetch through to the downloader. Without this the
  // downloader silently used the global fetch while the registry used the
  // injected one, so a test could never exercise the download path — and a
  // "download failed" assertion would pass because the REAL network refused a
  // fake URL, not because the code under test rejected anything.
  const downloaded = await downloadExtensionPayload(entry.download, stagingDir, {
    ...options.download,
    fetchImpl: options.download?.fetchImpl ?? options.fetchImpl,
  });
  if (!downloaded.ok) {
    try { fs.rmSync(stagingDir, { recursive: true, force: true }); } catch { /* best effort */ }
    return { ok: false, error: 'download_failed', errors: downloaded.errors };
  }

  // Run the SAME staging the folder install uses, so a registry install and a
  // folder install converge on one validated path rather than two.
  const staged = stageFromDirectory(stagingDir);
  if (!staged.ok) {
    try { fs.rmSync(stagingDir, { recursive: true, force: true }); } catch { /* best effort */ }
    return { ok: false, error: 'stage_failed', errors: staged.errors };
  }

  return {
    ok: true,
    id,
    payloadDir: staged.payloadDir!,
    manifestJson: staged.manifestJson,
    warnings: staged.warnings ?? [],
  };
}
