// The nine-mode catalog: one representative request per use case, with the
// visual it should get. `view` is the registry view (visualCatalog.mjs); a
// chart also names what it is for. `alt` lists other acceptable views where the
// catalog itself offers two (a table OR a chart, a process OR a funnel).
//
// Used by the resolver tests (every row), the wiring E2E (one or two per mode)
// and the opt-in live check (a subset).
export const MODE_CATALOG = {
  general: [
    { q: 'Map how a request gets approved.', view: 'flowchart' },
    { q: 'Help us compare these options.', view: 'matrix' },
    { q: 'Organize the ideas we discussed.', view: 'mindmap' },
    { q: 'Show the important milestones.', view: 'timeline' },
    { q: 'Who owns what and who depends on whom?', view: 'responsibility', alt: ['dependency'] },
    { q: 'Show how the budget is split.', view: 'chart', chartIntent: 'breakdown' },
    { q: 'Plot how this metric changed.', view: 'chart', chartIntent: 'trend' },
    { q: 'What happens if this decision changes?', view: 'decision' },
  ],
  'looking-for-work': [
    { q: 'Summarize my career progression.', view: 'timeline' },
    { q: 'Help me structure that behavioral answer.', view: 'flowchart' },
    { q: 'Map my experience to this job.', view: 'matrix' },
    { q: 'Draw the project I just described.', view: 'architecture', alt: ['flowchart', 'sequence'] },
    { q: 'Show my application stages.', view: 'flowchart', alt: ['state'] },
    { q: 'Compare these offers.', view: 'matrix', alt: ['chart'] },
    { q: 'Plan interview preparation.', view: 'gantt', alt: ['timeline', 'flowchart'] },
    { q: 'Map the follow-up steps after this interview.', view: 'flowchart', alt: ['timeline'] },
  ],
  'technical-interview': [
    { q: 'Design a notification service.', view: 'architecture' },
    { q: 'Model users, orders, and payments.', view: 'er' },
    { q: 'Design the objects for a parking lot.', view: 'class' },
    { q: 'Show the checkout request sequence.', view: 'sequence' },
    { q: 'Visualize the algorithm.', view: 'flowchart' },
    { q: 'Show the order lifecycle.', view: 'state' },
    { q: 'Construct this DFA.', view: 'automaton' },
    { q: 'Map deployment and data movement.', view: 'architecture' },
    { q: 'Compare the scaling cost or complexity.', view: 'matrix', alt: ['chart'] },
  ],
  sales: [
    { q: 'Show the current workflow and the proposed one.', view: 'flowchart' },
    { q: 'What would revenue look like at 5% monthly growth?', view: 'chart', chartIntent: 'forecast' },
    { q: 'Show the expected savings and break-even.', view: 'chart', chartIntent: 'breakeven' },
    { q: 'Where are deals dropping out?', view: 'chart', chartIntent: 'funnel' },
    { q: 'Map who is involved in buying.', view: 'responsibility' },
    { q: 'Help navigate this objection.', view: 'decision' },
    { q: 'Show implementation and rollout.', view: 'gantt', alt: ['timeline'] },
    { q: 'Compare adoption or retention patterns.', view: 'chart', chartIntent: 'trend' },
    { q: 'Show how the product integrates with their systems.', view: 'architecture', alt: ['sequence'] },
  ],
  recruiting: [
    { q: "Map this candidate's experience to the role.", view: 'matrix' },
    { q: "Show the candidate's career timeline.", view: 'timeline' },
    { q: 'Structure the interview stages.', view: 'flowchart', alt: ['state'] },
    { q: 'Map the recruiting pipeline.', view: 'chart', chartIntent: 'funnel', alt: ['flowchart'] },
    { q: 'Which requirements need follow-up evidence?', view: 'matrix' },
    { q: 'Who interviews which area?', view: 'responsibility' },
    { q: 'Plan the remaining interview schedule.', view: 'gantt', alt: ['timeline'] },
    { q: 'Map the offer-to-onboarding process.', view: 'flowchart', alt: ['state'] },
  ],
  'team-meet': [
    { q: 'Show which work blocks which.', view: 'dependency' },
    { q: 'Turn the action items into a plan.', view: 'gantt', alt: ['flowchart', 'matrix'] },
    { q: 'Map the decisions and alternatives.', view: 'dependency', alt: ['decision'] },
    { q: 'Draw the architecture we agreed on.', view: 'architecture', basis: 'meeting-reconstruction' },
    { q: 'Show the revised data model.', view: 'er', alt: ['class'] },
    { q: 'Show release milestones.', view: 'timeline', alt: ['gantt'] },
    { q: 'Compare effort and impact.', view: 'matrix', alt: ['chart'] },
    { q: 'Visualize sprint or incident metrics.', view: 'chart', chartIntent: 'trend' },
    { q: 'Compare resource or capacity plans.', view: 'chart', chartIntent: 'comparison', alt: ['matrix'] },
  ],
  lecture: [
    { q: 'Organize these concepts.', view: 'mindmap' },
    { q: 'Show how this process works.', view: 'flowchart' },
    { q: 'Explain the cycle or lifecycle with a diagram.', view: 'state', alt: ['flowchart'] },
    { q: 'Show the interaction order as a sequence diagram.', view: 'sequence' },
    { q: "Draw the ER model in the professor's notation.", view: 'er', alt: ['chen'] },
    { q: 'Draw these classes and objects.', view: 'class' },
    { q: 'Show the DFA or NFA for this language.', view: 'automaton' },
    { q: 'Plot this equation or experimental result.', view: 'chart' },
    { q: 'Show the chronology or prerequisites.', view: 'timeline', alt: ['dependency'] },
  ],
  seminar: [
    { q: 'Draw the method described in this paper.', view: 'flowchart' },
    { q: 'Map the proposed conceptual framework.', view: 'mindmap', alt: ['dependency'] },
    { q: 'Show the claim and supporting evidence.', view: 'dependency', alt: ['matrix'] },
    { q: 'Compare the baselines and proposed method.', view: 'matrix', alt: ['chart'] },
    { q: 'Reproduce this result figure as a chart.', view: 'chart' },
    { q: 'Show the protocol or experimental sequence.', view: 'flowchart', alt: ['sequence'] },
    { q: 'Map the study phases.', view: 'gantt', alt: ['timeline'] },
    { q: 'Reconstruct the diagram on this slide.', view: 'flowchart', alt: ['architecture', 'sequence', 'state', 'er', 'class'], basis: 'source-reconstruction' },
  ],
  'call-center': [
    { q: 'Walk me through diagnosing this issue.', view: 'decision' },
    { q: 'Show where this case stands.', view: 'state' },
    { q: 'Show the escalation path for this case.', view: 'responsibility', alt: ['sequence'] },
    { q: "Map the customer's resolution journey.", view: 'flowchart' },
    { q: 'Show the sequence of events.', view: 'timeline', alt: ['sequence'] },
    { q: 'Explain the refund or eligibility path.', view: 'decision' },
    { q: 'Explain the bill or usage change.', view: 'chart', chartIntent: 'breakdown' },
    { q: 'Show repeat issues or service-level trends.', view: 'chart', chartIntent: 'trend' },
  ],
};

/** Requests that must NOT get a visual in that mode (prose is the right answer). */
export const MODE_NEGATIVES = {
  general: ['What time works for everyone next week?', 'Can you summarize what they just said?'],
  'looking-for-work': ['Tell me about a time you disagreed with a teammate.', 'Walk me through your career progression.', 'What is your biggest weakness?'],
  'technical-interview': ['Write a function to solve two sum.', 'What is a hash table and when would you use one?', 'What is a DFA?'],
  sales: ['How do I handle the pricing objection in one sentence?', 'What does the enterprise plan include?'],
  recruiting: ['What should I ask about their leadership experience?', 'Is this candidate a good fit?'],
  'team-meet': ['Can you give us a status update on the migration?', 'What did we decide about the release date?'],
  lecture: ['What is gradient descent?', 'Can you explain that again more simply?', 'There are three stages in this process.'],
  seminar: ['What is the main contribution of this paper?', 'What sample size did they use?'],
  'call-center': ['My internet has been down since morning, what is going on?', 'What is your return policy for opened items?'],
};

/**
 * System-design asks that contain a word from the visual catalog (chart, graph,
 * timeline, funnel, schema, class …) naming the SYSTEM, not a picture. Each is
 * paired with the view the system-design feature gave it before the catalog
 * existed; the catalog must not change any of them.
 */
export const SYSTEM_DESIGN_ASKS = Object.freeze([
  ["Design a real-time analytics dashboard with charts", "architecture"],
  ["Design a class registration system for a university", "architecture"],
  ["Design a metrics pipeline that produces trend charts", "architecture"],
  ["Design a schema migration service", "architecture"],
  ["Design a ticket escalation system", "architecture"],
  ["Design a mind mapping app like Miro", "architecture"],
  ["Design a calendar scheduling system", "architecture"],
  ["Design a funnel tracking system for marketing", "architecture"],
  ["Design a comparison shopping engine", "architecture"],
  ["Design a graph database", "architecture"],
  ["Design a social graph service", "architecture"],
  ["Design a stock chart service like TradingView", "architecture"],
  ["Design a state machine service for workflows", "state"],
  ["Design a decision engine for fraud", "architecture"],
  ["Design a dependency resolution service like npm", "architecture"],
  ["Design a workflow orchestration platform", "flowchart"],
  ["Design a system to track project milestones", "architecture"],
  ["Design a break-even calculator API", "architecture"],
  ["Design a forecasting service for demand", "architecture"],
  ["Design YouTube", "architecture"],
  ["Design a distributed queue", "architecture"],
  ["How would you design a leaderboard?", "architecture"],
  ["Design a table reservation system", "architecture"],
  ["Design a matrix multiplication service", "architecture"],
  ["Design a roadmap planning tool", "architecture"],
  ["Design Twitter's home timeline. Go deep: fan-out, caching, storage, and how you'd handle celebrities.", "architecture"],
  ["Design a news feed timeline service", "architecture"],
  ["How would you build the Instagram timeline?", "architecture"],
  ["Design an order tracking system with status updates", "architecture"],
  ["Design a CRM pipeline service for sales stages", "architecture"],
  ["Design a cohort analysis backend", "architecture"],
  ["Design a customer support ticketing system", "architecture"],
  ["Design a system for scheduling interviews", "architecture"],
  ["Design a lecture streaming platform", "architecture"],
  ["Design a troubleshooting assistant backend", "architecture"],
  ["Design a pricing comparison API", "architecture"],
  ["Design a trend detection service for Twitter", "architecture"],
  ["Design a budget tracking app", "architecture"],
  ["Design a org directory service", "architecture"],
  ["Design a project planning tool like Jira", "architecture"],
  ["Design a survey results aggregation service", "architecture"],
  ["Design an event timeline API for audit logs", "architecture"],
  ["Design a growth analytics platform", "architecture"],
  ["Design a savings account ledger", "architecture"],
  ["Design a class diagram editor", "architecture"],
  ["Design a dependency graph service for builds", "architecture"],
  ["Design an escalation policy engine like PagerDuty", "architecture"],
  ["Design a payment retry state machine", "state"],
  ["Design a process scheduler", "flowchart"],
]);

/**
 * Ordinary questions that contain a word from the catalog (graph, chart, plot,
 * timeline, forecast, funnel, class diagram …) and are NOT asking for a
 * picture: [question, mode, planner answer type]. None may draw.
 */
export const CATALOG_WORD_NEGATIVES = Object.freeze([
  ["Find the shortest path in a weighted graph.", "technical-interview", "dsa_question_answer"],
  ["Given a graph, detect whether it has a cycle.", "technical-interview", "dsa_question_answer"],
  ["Implement BFS on a graph", "technical-interview", "dsa_question_answer"],
  ["Write a function that plots a histogram with matplotlib", "technical-interview", "coding_question_answer"],
  ["How do you traverse a binary tree?", "technical-interview", "dsa_question_answer"],
  ["Explain the difference between a tree and a graph", "technical-interview", "general_meeting_answer"],
  ["What is a decision tree in machine learning?", "lecture", "general_meeting_answer"],
  ["What is your experience with Gantt charts?", "looking-for-work", "general_meeting_answer"],
  ["Tell me about the timeline of your last project", "looking-for-work", "general_meeting_answer"],
  ["Have you used funnels to analyse conversion?", "looking-for-work", "general_meeting_answer"],
  ["Can you chart a path forward for the team?", "team-meet", "general_meeting_answer"],
  ["What does the graph on this slide show?", "lecture", "general_meeting_answer"],
  ["Is the forecast still on track for Q4?", "sales", "general_meeting_answer"],
  ["What is the timeline for delivery?", "sales", "general_meeting_answer"],
  ["Did you see the chart I sent yesterday?", "team-meet", "general_meeting_answer"],
  ["Clone a graph given a reference to a node", "technical-interview", "dsa_question_answer"],
  ["Design a class hierarchy for shapes in Python and write the code", "technical-interview", "coding_question_answer"],
  ["What is the state of the pipeline?", "sales", "general_meeting_answer"],
  ["Is the ERD up to date?", "team-meet", "general_meeting_answer"],
  ["Where is the class diagram stored?", "team-meet", "general_meeting_answer"],
  ["The charts in the deck looked great.", "sales", "general_meeting_answer"],
  ["We missed the forecast last quarter.", "sales", "general_meeting_answer"],
  ["Reverse a linked list", "technical-interview", "dsa_question_answer"],
  ["Topological sort of a dependency graph in Python", "technical-interview", "dsa_question_answer"],
  ["How does a finite automaton differ from a regex engine?", "technical-interview", "general_meeting_answer"],
  ["What is the difference between an NFA and a DFA?", "lecture", "general_meeting_answer"],
  ["Do we have a funnel problem?", "sales", "general_meeting_answer"],
  ["Who owns the roadmap?", "team-meet", "general_meeting_answer"],
]);
