// Decisions of the visual resolver, one sentence at a time: every example the
// 2026-10-01 review reproduced a wrong decision for, with the decision it
// should get. 29 of these 141 came out right before the rules were rewritten.
//
// [question, { mode, answerType, active, instructions }, expectation]
// expectation: 'off' | view string | { view, operation, basis, output, withCode, parent }
export const ARCH = {
  artifactId: 'design-1.v1', artifact: 'mermaid', view: 'architecture', version: 1, foreground: true,
  source: ['flowchart LR', '    producer["Producer Service"] -->|"enqueue"| queue["Notification Queue"]', '    queue --> worker["Delivery Worker"]', '    worker -->|"send"| provider["Email / SMS Provider"]', '    worker --> db[("Delivery Log")]'].join('\n'),
};
export const CHART = {
  artifactId: 'design-2.v1', artifact: 'chart', view: 'chart', version: 1, foreground: true,
  source: JSON.stringify({ v: 1, type: 'line', title: 'Revenue at 5% monthly growth', x: { label: 'Month' }, y: { label: 'Revenue', unit: 'USD' }, compute: { kind: 'compound_growth', baseline: 10000, ratePercent: 5, period: 'month', periods: 3 }, assumptions: ['Net growth stays at 5%'] }),
};
const li = { mode: 'looking-for-work' };
const ti = { mode: 'technical-interview' };
export const CASES = [
  // C1 — unrelated lines with a design on the table
  ['Can you add me on LinkedIn?', { ...li, active: ARCH }, 'off'],
  ["Let's move on to pricing.", { mode: 'sales', active: ARCH }, 'off'],
  ['Set up a meeting for Tuesday.', { ...li, active: ARCH }, 'off'],
  ['How do we handle the offer?', { ...li, active: ARCH }, 'off'],
  ['What time is it?', { ...li, active: ARCH }, 'off'],
  ['What is your email?', { ...li, active: ARCH }, 'off'],
  ['Shorter hours would be nice.', { ...li, active: ARCH }, 'off'],
  ['Is this a remote role?', { ...li, active: ARCH }, 'off'],
  ['Change the greeting to Hello', { ...li, active: ARCH }, 'off'],
  ['Use a friendlier tone', { ...li, active: ARCH }, 'off'],
  ['Does it support SSO?', { mode: 'sales', active: CHART }, 'off'],
  ['Is the table sorted?', { ...ti, answerType: 'coding_question_answer', active: { ...ARCH, foreground: false } }, 'off'],
  ['Use a queue instead of recursion', { ...ti, answerType: 'coding_question_answer', active: { ...ARCH, foreground: false } }, 'off'],
  // …and the follow-ups that must still work
  ['Add Redis between the worker and the provider', { ...ti, active: ARCH }, { operation: 'update' }],
  ['Add a dead-letter queue', { ...ti, active: ARCH }, { operation: 'update' }],
  ['Add retry handling and a dead-letter queue', { ...ti, active: ARCH }, { operation: 'update' }],
  ['Make this multi-region', { ...ti, active: ARCH }, { operation: 'update' }],
  ['Replace Kafka with RabbitMQ', { ...ti, active: ARCH, answerType: 'coding_question_answer' }, { operation: 'update' }],
  ['How does this scale to ten million users?', { ...ti, active: ARCH }, { operation: 'update' }],
  ['Why do we need the queue?', { ...ti, active: ARCH }, { operation: 'explain' }],
  ['Why did you add the queue?', { ...ti, active: ARCH }, { operation: 'explain' }],
  ['Why is this better than polling?', { ...ti, active: ARCH }, { operation: 'explain' }],
  ['Show that as a sequence diagram.', { ...ti, active: ARCH }, { view: 'sequence', parent: true }],
  ['Draw this again', { ...ti, active: ARCH }, { parent: true }],
  ['Draw this again', { ...ti, active: ARCH, answerType: 'system_design_answer' }, { parent: true }],
  ['Sketch it', { ...ti, active: ARCH, answerType: 'system_design_answer' }, { parent: true }],
  ['Make it shorter', { ...ti, active: ARCH }, { operation: 'refine' }],
  ['shorten', { ...ti, active: ARCH }, { operation: 'refine' }],
  ['Make it shorter', { ...ti, active: { ...ARCH, foreground: false } }, 'off'],
  ['Why do we need the queue?', { ...ti, active: { ...ARCH, foreground: false } }, { operation: 'explain' }],
  ['Make it 3%', { mode: 'sales', active: CHART }, { operation: 'update', view: 'chart' }],
  ['Change growth to 3%', { mode: 'sales', active: CHART }, { operation: 'update', view: 'chart' }],
  ['What would revenue look like at 8% monthly growth?', { mode: 'sales', active: CHART }, { operation: 'update', view: 'chart' }],
  ['And at 8%?', { mode: 'sales', active: CHART }, { operation: 'update', view: 'chart' }],
  ['Now do it with churn of 2%.', { mode: 'sales', active: CHART }, { operation: 'update', view: 'chart' }],
  ['Why is the last month higher?', { mode: 'sales', active: CHART }, { operation: 'explain' }],
  // M4 — a cue of another kind is not an edit of this one
  ['Add a forecast.', { ...ti, active: ARCH }, 'off'],
  // M6 — a fresh subject is a fresh drawing
  ['Show the TCP handshake sequence.', { ...ti, active: ARCH }, { view: 'sequence', parent: false }],
  ['Draw a diagram of how DNS works, I need to explain it.', { ...ti, active: ARCH }, { parent: false }],
  ['Just draw the OAuth login flow.', { ...ti, active: ARCH }, { parent: false }],
  // H2 (main) — coding questions after a design
  ['Merge two sorted arrays', { ...ti, answerType: 'coding_question_answer', active: ARCH }, 'off'],
  ['Remove nth node from end of linked list', { ...ti, answerType: 'dsa_question_answer', active: ARCH }, 'off'],
  ['Insert into a binary search tree', { ...ti, answerType: 'dsa_question_answer', active: ARCH }, 'off'],
  ['Use a hash map to find two numbers that add up to a target', { ...ti, answerType: 'dsa_question_answer', active: ARCH }, 'off'],
  ['Use a queue to implement BFS', { ...ti, answerType: 'dsa_question_answer', active: ARCH }, 'off'],
  // C2 — coding questions
  ['Given the schema users(id, name) and orders(id, user_id), find users with no orders.', { ...ti, answerType: 'dsa_question_answer' }, 'off'],
  ['Create a decision tree classifier from scratch.', { ...ti, answerType: 'dsa_question_answer' }, 'off'],
  ['What will the heap look like after 3 pops?', { ...ti, answerType: 'dsa_question_answer' }, 'off'],
  ['The array grows by 2 each time it fills, what is the amortised cost of append?', { ...ti, answerType: 'dsa_question_answer' }, 'off'],
  ['Build a graph of the dependencies and find cycles.', { ...ti, answerType: 'dsa_question_answer' }, 'off'],
  ['Simulate a DFA on an input string.', { ...ti, answerType: 'dsa_question_answer' }, 'off'],
  ['Plot twist: now do it in O(1) space.', { ...ti, answerType: 'dsa_question_answer' }, 'off'],
  ['Design an LRU cache.', { ...ti, answerType: 'dsa_question_answer' }, 'off'],
  ['Design a hit counter.', { ...ti, answerType: 'coding_question_answer' }, 'off'],
  ['Draw the output on the canvas using the 2D context.', { ...ti, answerType: 'coding_question_answer' }, 'off'],
  ['Sketch the recursion in pseudocode.', { ...ti, answerType: 'dsa_question_answer' }, 'off'],
  ['Write a function to draw a circle', { ...ti, answerType: 'coding_question_answer' }, 'off'],
  ['Design a payment API and show the handler code in TypeScript.', { ...ti, answerType: 'coding_question_answer' }, { view: 'architecture', withCode: true }],
  ['Model users, orders, and payments.', { ...ti, answerType: 'coding_question_answer' }, { view: 'er' }],
  ['Design the objects for a parking lot.', { ...ti, answerType: 'coding_question_answer' }, { view: 'class' }],
  ['Draw a flowchart of binary search', { ...ti, answerType: 'dsa_question_answer' }, { view: 'flowchart' }],
  // H1 — drawing verbs that do not draw
  ['Can you illustrate that with an example?', li, 'off'],
  ['What conclusions did you draw from the data?', li, 'off'],
  ['How do you draw the line between speed and quality?', li, 'off'],
  ['How do you feel about whiteboard interviews?', li, 'off'],
  ['We need to map out the next quarter.', { mode: 'team-meet' }, 'off'],
  ['I can not visualise myself in that role.', li, 'off'],
  // H2 — a verb somewhere and a noun somewhere
  ['Did you ever have to present a forecast to leadership?', li, 'off'],
  ['How do you make sure prerequisites are met before a launch?', { mode: 'team-meet' }, 'off'],
  ['How do you make sure the schema stays backwards compatible?', ti, 'off'],
  ['Can you give me a timeline for delivery?', { mode: 'sales' }, 'off'],
  ['Give me a second, I am pulling up the chart.', { mode: 'team-meet' }, 'off'],
  ['Project timeline is at risk.', { mode: 'team-meet' }, 'off'],
  ['Summarise the release plan in one sentence.', { mode: 'team-meet' }, 'off'],
  ['Let us compare the options offline.', { mode: 'team-meet' }, 'off'],
  // H3 — a notation word alone
  ['What did Chen say about the release?', { mode: 'team-meet' }, 'off'],
  ['Ask Chen to send the deck.', { mode: 'team-meet' }, 'off'],
  ['The DFA accepts strings ending in ab.', { mode: 'lecture' }, 'off'],
  ['How many states does the DFA need?', { mode: 'lecture' }, 'off'],
  ['The class diagram is outdated.', { mode: 'team-meet' }, 'off'],
  ['We use UML for that.', { mode: 'team-meet' }, 'off'],
  ['The ERD is out of date.', { mode: 'team-meet' }, 'off'],
  ['We used a mind map during the workshop.', { mode: 'team-meet' }, 'off'],
  // H4 — statements that mention a thing
  ['The handoff went fine.', { mode: 'team-meet' }, 'off'],
  ['Let us update the dependencies in package.json.', { mode: 'team-meet' }, 'off'],
  ['We need to update the schema.', { mode: 'team-meet' }, 'off'],
  ['The lifecycle hooks are broken in the new version.', { mode: 'team-meet' }, 'off'],
  ['Our sales pipeline is pretty healthy this quarter.', { mode: 'sales' }, 'off'],
  ['We saw 5% monthly growth last quarter.', { mode: 'sales' }, 'off'],
  ['So what does your typical sprint look like with 2 week iterations?', { mode: 'team-meet' }, 'off'],
  ['Who signs off on the budget?', { mode: 'sales' }, 'off'],
  ['Can you schedule the release for Friday?', { mode: 'team-meet' }, 'off'],
  // H5 — mentions of design
  ['The system design round is tomorrow.', li, 'off'],
  ['How do you prepare for system design interviews?', li, 'off'],
  ['What is the overall architecture of the app?', li, 'off'],
  ['Why did you design the API that way?', li, 'off'],
  ['How would you scale the team that owns the payments service?', li, 'off'],
  ['How would you structure a 30 minute chat with a skip-level?', li, 'off'],
  ['How do we build a pipeline of candidates?', { mode: 'recruiting' }, 'off'],
  ['The high-level design of the service was approved.', { mode: 'team-meet' }, 'off'],
  // H6 — the named diagram, not a chart of numbers
  ['Draw a flow chart of the login process.', ti, 'flowchart'],
  ['Create a Gantt chart for the rollout.', { mode: 'team-meet' }, 'gantt'],
  ['Draw an org chart for the team.', { mode: 'team-meet' }, 'responsibility'],
  ['Draw a state chart for the order.', ti, 'state'],
  ['Draw a UML sequence diagram of login.', ti, 'sequence'],
  // H7 — basis
  ['Design a real-time chat system.', { ...ti, answerType: 'system_design_answer' }, { basis: 'proposed-design' }],
  ['Draw a real-time chat architecture.', ti, { basis: 'proposed-design' }],
  ['Design an API for our actual customers.', { ...ti, answerType: 'system_design_answer' }, { basis: 'proposed-design' }],
  ['Design a URL shortener. We discussed scale earlier.', { ...ti, answerType: 'system_design_answer' }, { basis: 'proposed-design' }],
  ['Draw our actual architecture from the doc', ti, { basis: 'source-reconstruction' }],
  ['Turn the system we just discussed into an architecture diagram', ti, { basis: 'meeting-reconstruction' }],
  // H8 — "no diagram"
  ["Don't draw anything, just give me the answer.", ti, 'off'],
  ['Design a URL shortener, no need for a diagram.', { ...ti, answerType: 'system_design_answer' }, { output: 'text-only' }],
  ["Design a URL shortener. I don't want a diagram.", { ...ti, answerType: 'system_design_answer' }, { output: 'text-only' }],
  ['Compare these options, no table please.', { mode: 'general' }, 'off'],
  ['Draw the architecture and just explain the write path briefly.', ti, { output: 'text-and-diagram' }],
  ['There is no diagram in the doc, so draw the architecture from the doc.', ti, { output: 'text-and-diagram' }],
  ['Draw the login sequence.', { ...ti, instructions: 'Just tell me what to say, in first person.' }, { view: 'sequence' }],
  ['Draw the login sequence.', { ...ti, instructions: 'Answer in plain text only.' }, { view: 'sequence' }],
  ['Design a URL shortener.', { ...ti, answerType: 'system_design_answer', instructions: 'No diagrams please.' }, { output: 'text-only' }],
  // H9 — explicit requests
  ['Can you put that in a table?', { mode: 'general' }, 'matrix'],
  ['Make a table comparing the three vendors.', { mode: 'general' }, 'matrix'],
  ['I need a diagram.', { mode: 'general' }, 'flowchart'],
  ['A diagram would help here.', { mode: 'general' }, 'flowchart'],
  ['Can I see a flowchart of the login process?', { mode: 'general' }, 'flowchart'],
  ['Explain DNS using diagrams.', { mode: 'lecture' }, 'flowchart'],
  ['Show this graphically.', { mode: 'general' }, 'flowchart'],
  ['Map this out.', { mode: 'general' }, 'flowchart'],
  ['Bar chart of signups by month please.', { mode: 'general' }, 'chart'],
  ['What is the ER diagram for a library system?', ti, 'er'],
  ['Given your experience with distributed systems, how would you design a URL shortener?', { ...ti, answerType: 'system_design_answer' }, 'architecture'],
  ['Design a rate limiter. Have you built one before?', { ...ti, answerType: 'system_design_answer' }, 'architecture'],
  // H10 — output constraints
  ['Design a rate limiter, code only.', { ...ti, answerType: 'system_design_answer' }, { output: 'text-and-diagram' }],
  ['Design a notification system for users who get no text messages.', { ...ti, answerType: 'system_design_answer' }, { output: 'text-and-diagram' }],
  ['Design a URL shortener. There is no description in the ticket.', { ...ti, answerType: 'system_design_answer' }, { output: 'text-and-diagram' }],
  ['I used Mermaid source files at my last job.', li, 'off'],
  ['Design a URL shortener, diagram only.', { ...ti, answerType: 'system_design_answer' }, { output: 'diagram-only' }],
  ['Just give me the Mermaid for a URL shortener design.', ti, { output: 'source-only' }],
  // M7 — nouns that are not code requests
  ['Design a promo code system.', { ...ti, answerType: 'system_design_answer' }, { withCode: false }],
  ['Add a promo code service.', { ...ti, active: ARCH }, { operation: 'update' }],
  ['What is the function of the queue?', { ...ti, active: ARCH }, { operation: 'explain' }],
];
