// Ordinary talk, for the visual resolver (src/lib/diagram/diagramRequest.mjs).
//
// Built during the 2026-10-01 review, when the resolver drew for far too much:
// with a diagram on the table, 49 of the 65 lines in UNRELATED_FOLLOW_UPS were
// read as edits of it; coding questions were handed a chart contract; "did you
// ever have to present a forecast?" was a request for a forecast.
//
// CORPUS             what people say in interviews and meetings. None of it
//                    asks for a picture in so many words (a few lines imply one in
//                    the right mode: those are named in the tests).
// EXPLICIT           clear requests for a visual, in many phrasings.
// CODING_QUESTIONS   questions a coding round asks.
// UNRELATED_FOLLOW_UPS  what gets said next, after a diagram, that is not about it.

export const CORPUS = Object.freeze({
  behavioural: [
    "Tell me about yourself.",
    "Tell me about a time you had to deal with a difficult stakeholder.",
    "Tell me about a time you missed a deadline.",
    "Describe a situation where you had to make a decision without all the information.",
    "What is your biggest weakness?",
    "Why do you want to work here?",
    "Where do you see yourself in five years?",
    "How do you handle conflict on a team?",
    "Give me an example of a time you showed leadership.",
    "Give me an example of a project that failed and what you learned.",
    "Walk me through your resume.",
    "Walk me through your career path so far.",
    "Can you walk me through your career history?",
    "What is the project you are most proud of?",
    "How do you prioritise when everything is urgent?",
    "How do you plan your week?",
    "How do you structure your day?",
    "How do you make decisions under pressure?",
    "What would your manager say about you?",
    "Why are you leaving your current role?",
    "What are your salary expectations?",
    "How do you handle feedback?",
    "Describe your process for onboarding onto a new codebase.",
    "What was the timeline of that project?",
    "How did you measure success on that project?",
    "What were the key milestones on that project?",
    "How did the team grow while you were there?",
    "What does your ideal onboarding process look like?",
    "How did you handle dependencies on other teams?",
    "Tell me about a time you had to hand off a project.",
    "How do you plan a release?",
    "What is your experience with data modelling?",
    "Tell me about a time you improved a process.",
    "How do you compare the two offers you have right now?",
    "Did you ever have to present a forecast to leadership?",
    "What is your approach to troubleshooting production issues?",
    "How would you handle this objection from a senior engineer?",
    "What happened when your growth targets were missed by 10 percent?",
    "What would your first 90 days look like here?",
    "What would the next 3 months look like for you?",
    "So what does your typical sprint look like with 2 week iterations?",
    "What is your notice period?",
    "Do you have any questions for us?",
    "How do you stay organised?",
    "Who is involved in your code review process?",
    "Who approves your pull requests?",
    "Who is responsible for deployments on your team?",
    "How do you make sure prerequisites are met before a launch?",
    "I grew the team by 40 percent over two years.",
    "We grew revenue by 20% year over year while I was there.",
  ],
  dsa: [
    "Reverse a linked list.",
    "Find the shortest path in a weighted graph.",
    "Given a binary tree, return its level order traversal.",
    "Implement a trie with insert and search.",
    "Find the lowest common ancestor of two nodes in a binary tree.",
    "Given a matrix, rotate it 90 degrees clockwise.",
    "Search a 2D matrix that is sorted row-wise and column-wise.",
    "Spiral order traversal of a matrix.",
    "Implement an LRU cache.",
    "Design a hash map from scratch.",
    "Design a hash table.",
    "Merge k sorted lists.",
    "Given an array of meeting time intervals, find the minimum number of rooms required.",
    "Course schedule: given prerequisites, determine if you can finish all courses.",
    "Given a list of tasks with dependencies, return a valid order.",
    "Task scheduler: given tasks and a cooldown n, return the least number of intervals.",
    "Implement a queue using two stacks.",
    "Find the longest increasing subsequence.",
    "Longest common subsequence of two strings.",
    "Is this sequence a valid parenthesis string?",
    "Check whether a number sequence is an arithmetic progression.",
    "Count the number of islands in a grid.",
    "Find the kth largest element in an array.",
    "Detect a cycle in a linked list.",
    "Validate a binary search tree.",
    "Serialize and deserialize a binary tree.",
    "Implement Dijkstra.",
    "Given a state machine described as a table, find whether a string is accepted.",
    "Design a class for a deck of cards.",
    "Design the classes for a library management system.",
    "Design a parking lot using object oriented design.",
    "What is the time complexity of this algorithm?",
    "Can you explain the algorithm step by step?",
    "Walk me through the algorithm step by step.",
    "What data structure would you use to model a social network?",
    "How would you model a chess board?",
    "Model a deck of cards in code.",
    "How would you represent a graph in memory?",
    "Given a table of employees, write a SQL query to find the second highest salary.",
    "Write a SQL query that joins the orders table and the customers table.",
    "Find the dependency order of packages.",
    "Build a tree from inorder and preorder traversal.",
    "Construct a binary tree from a sorted array.",
    "Generate all permutations of a string.",
    "Create a decision tree classifier from scratch.",
    "Given the schema users(id, name) and orders(id, user_id), find users with no orders.",
    "Implement a state machine for a vending machine.",
    "Implement a timeline feature that returns the 10 most recent tweets.",
    "Design a data structure that supports insert, delete and getRandom in O(1).",
    "Explain how a B-tree index works.",
    "How does the pipeline of map, filter and reduce work?",
    "Plot twist: now do it in O(1) space.",
    "Now make it iterative.",
    "What if the input has 10 percent duplicates?",
    "What about when the array grows by 50%?",
    "Sliding window maximum.",
    "Compare the two approaches.",
    "Compare the complexity of quicksort and mergesort.",
    "Which approach is better, and what are the tradeoffs?",
    "Can you structure your solution into smaller functions?",
    "Can you outline your approach before coding?",
    "Can you summarize your approach?",
    "Then map each character to its frequency.",
    "And then plot the complexity in your head, is it n log n?",
    "Could you model the problem as a graph?",
    "Can you model this as a dynamic programming problem?",
    "Let us plan the approach first.",
    "Show me how you would handle the edge cases.",
    "Show me the recursion tree complexity.",
    "Give me the recurrence relation.",
    "Make a table of the dp states in your head, what is dp[i][j]?",
    "How would you find the process with the highest memory usage?",
    "Implement a workflow engine in Python.",
    "Write an algorithm to detect the lifecycle state of an order.",
    "What is the lifecycle of a React component?",
    "What is the lifecycle of a goroutine?",
  ],
  trivia: [
    "What is the difference between a process and a thread?",
    "What is a closure in JavaScript?",
    "Explain the event loop.",
    "How does garbage collection work in Java?",
    "What is the virtual DOM?",
    "What are React hooks?",
    "Explain how HTTPS works.",
    "What happens when you type a URL into the browser?",
    "How does the TLS handshake work?",
    "What is the difference between TCP and UDP?",
    "Explain the request lifecycle in Django.",
    "How does OAuth login flow work?",
    "Explain the authentication flow in your app.",
    "What is dependency injection?",
    "How do you manage dependencies in a monorepo?",
    "What is a database schema migration?",
    "What is the difference between SQL and NoSQL?",
    "What is database normalisation?",
    "What is an index and when would you use one?",
    "Explain CAP theorem.",
    "What is eventual consistency?",
    "How does Kafka guarantee ordering?",
    "What is a class in Python?",
    "What are abstract classes and objects for?",
    "Explain inheritance versus composition.",
    "What is object-oriented design?",
    "What is the CI/CD pipeline you use?",
    "How does a load balancer work?",
    "What is sharding?",
    "What is a state machine?",
    "Explain the Kubernetes pod lifecycle.",
    "What is the difference between an ER diagram and a class diagram?",
    "When would you use a sequence diagram?",
    "Do you use UML at work?",
    "What is the workflow for code review on your team?",
    "How does git rebase work?",
    "What is your git workflow?",
    "Explain how a hash table handles collisions.",
    "Describe the process of a database transaction.",
    "How does the handshake in WebSocket work?",
    "What is the architecture of React Native?",
    "Explain the architecture of your last project.",
    "What components make up a Kubernetes cluster?",
    "High-level, how does DNS work?",
    "What is a schema registry?",
    "What is a data model?",
    "How does the payment flow work in Stripe?",
    "How does message delivery flow work in WhatsApp?",
    "Explain the deployment process you used.",
    "What is the topology of your network?",
  ],
  systemDesignLegit: [
    "Design a URL shortener.",
    "Design a rate limiter.",
    "How would you design Instagram?",
    "Design a chat application.",
    "Design a notification system.",
  ],
  sales: [
    "What is your pricing?",
    "How much does the enterprise plan cost?",
    "That seems expensive compared to your competitor.",
    "We already use a competitor, why should we switch?",
    "What is the timeline for implementation?",
    "How long does onboarding take?",
    "Who else is involved in this decision?",
    "Who is involved in buying on your side?",
    "Who signs off on the budget?",
    "Who approves purchases over fifty thousand dollars?",
    "Our sales pipeline is pretty healthy this quarter.",
    "The deal pipeline looks good.",
    "How is your pipeline looking?",
    "We forecast about 2 million in ARR next year.",
    "Our forecast for Q4 is down.",
    "Can you send over the forecast?",
    "We are projecting revenue of 5 million next year.",
    "We saw 5% monthly growth last quarter.",
    "We are growing at 30 percent year over year.",
    "Our growth has been around 12% this year.",
    "What kind of ROI can we expect?",
    "When does it pay for itself?",
    "When do we break even on this?",
    "What is the payback period?",
    "Do you integrate with Salesforce?",
    "Does it have an integration with our systems?",
    "How does the product integrate with their systems?",
    "What does the rollout plan look like?",
    "Is there a discount for annual billing?",
    "We need to think about it.",
    "I need to talk to my boss first.",
    "Can you handle this objection: it is too expensive?",
    "We do not have budget right now.",
    "The budget is split between two departments.",
    "What are the next steps?",
    "What are the follow-up steps after this call?",
    "Let me check with procurement about the approval process.",
    "How does your approval process work?",
    "Our current workflow is mostly manual.",
    "Tell me about your current workflow.",
    "What is your existing workflow for invoices?",
    "We lose a lot of leads at the demo stage.",
    "Where are leads dropping?",
    "Our funnel is leaky at the top.",
    "The conversion between stages is low.",
    "Retention patterns have been flat.",
    "How do we increase retention?",
    "What does the handoff to customer success look like?",
    "What is the escalation path if something breaks?",
    "Can we compare the plans?",
    "Compare the two plans for me.",
    "Our numbers changed a lot since last year.",
    "How has the market changed over the last year?",
    "How did your pricing change?",
    "How has our usage changed?",
    "We have 500 users today and expect to grow at 10% a month.",
    "Thanks, that was helpful.",
    "Could you send me the deck?",
    "What dependencies do you have on our IT team?",
    "Are there any prerequisites before we start?",
    "What is blocking the contract?",
    "What happens if this decision changes?",
    "Is the forecast still on track for Q4?",
    "The cost breakdown is in the proposal.",
    "What is the cost breakdown?",
    "We want a pie chart in the QBR deck, do you have a template?",
    "The quadrant in the Gartner report puts you as a challenger.",
    "Are you in the Gartner magic quadrant?",
    "Our release schedule is tight.",
    "What is your release schedule?",
    "What is the trend you are seeing in the market over the last few years?",
  ],
  recruiting: [
    "Tell me about your experience with React.",
    "What is the interview process like?",
    "What are the interview stages?",
    "What are the application stages?",
    "Who will I be interviewing with?",
    "Who interviews for this role?",
    "What is the hiring pipeline like for this role?",
    "Our recruiting pipeline is full.",
    "What is the recruiting process?",
    "What are the requirements for this role?",
    "Does the candidate meet the requirements?",
    "What is the compensation range?",
    "How does compensation compare to market?",
    "Can you add me on LinkedIn?",
    "When can you start?",
    "What is your notice period?",
    "Is this candidate a good fit?",
    "What should I ask next?",
    "The candidate has five years of experience.",
    "What is the onboarding process?",
    "What does career progression look like here?",
    "What is the career path for this role?",
    "What is the interview schedule?",
    "Can we schedule the onsite for next week?",
    "Set up a meeting for Tuesday.",
    "What skills are must-have?",
    "Which requirements need a visa?",
    "Do you have any hand-offs with the hiring manager?",
    "The offer-to-onboarding handoff is slow.",
  ],
  teamMeet: [
    "What did you work on yesterday?",
    "Any blockers?",
    "What is blocking you?",
    "What is blocked right now?",
    "I am blocked on the API team.",
    "The migration has a dependency on the auth service.",
    "We have too many dependencies in this sprint.",
    "Let us update the dependencies in package.json.",
    "Who owns the roadmap?",
    "Who owns what on this project?",
    "Who is responsible for the release?",
    "Who handles on-call this week?",
    "Who is involved in the incident review?",
    "When is the release?",
    "What are the release milestones?",
    "The key milestones are in the doc.",
    "We hit all the major milestones.",
    "What is the project schedule?",
    "The release plan is in Confluence.",
    "Let us move on to pricing.",
    "Let us move on to the next topic.",
    "Can you give us a status update on the migration?",
    "What did we decide about the release date?",
    "The sprint metrics look fine.",
    "How did velocity change this sprint?",
    "How has the error rate changed since the deploy?",
    "The numbers changed after the fix.",
    "Did you see the chart I sent yesterday?",
    "The class diagram is outdated.",
    "Is the ERD up to date?",
    "We need to update the schema.",
    "The schema changed last week.",
    "Did someone change the database schema?",
    "The data model is getting complicated.",
    "What is the timeline for the migration?",
    "Timeline looks tight.",
    "I will send the action items after the call.",
    "Let us compare the options offline.",
    "Compare the two approaches quickly.",
    "We should compare the costs before deciding.",
    "What are the tradeoffs?",
    "The hand-off to QA happens on Thursday.",
    "The handoff went fine.",
    "We need a rollout plan.",
    "What is the rollout plan?",
    "Effort versus impact, I think this is low priority.",
    "This has high impact and low effort.",
    "The burndown looks bad.",
    "Can everyone hear me?",
    "Let us take this offline.",
    "What is the current workflow for incidents?",
    "The new workflow is live.",
    "The approval process is too slow.",
    "The lifecycle hooks are broken in the new version.",
    "We grew the cluster by 20% last month.",
    "Usage is growing at 15 percent a week.",
    "What will the cluster look like at 3x traffic?",
    "What would our costs look like with 200 more nodes?",
    "The incident timeline is in the postmortem.",
    "Capacity plans are due Friday.",
    "How do these ideas fit together?",
    "Let us plan the sprint.",
    "Let us plan the release.",
    "Can you schedule the release for Friday?",
    "We should plan the rollout carefully.",
  ],
  support: [
    "My internet has been down since morning.",
    "I want a refund.",
    "Am I eligible for a refund?",
    "What is your return policy?",
    "What is the refund policy path for digital goods?",
    "Why is my bill higher this month?",
    "Why did my bill go up?",
    "Can you explain the bill?",
    "I was charged twice.",
    "Where does my ticket stand?",
    "What is the ticket status?",
    "What is the case status?",
    "Can I speak to a manager?",
    "Who handles billing disputes?",
    "I already tried restarting the router.",
    "Can you help me troubleshoot this?",
    "I have been troubleshooting this for an hour.",
    "What are the troubleshooting steps?",
    "How do I cancel my subscription?",
    "What is the cancellation policy?",
    "Is this covered under warranty?",
    "What is the escalation path?",
    "How long will it take to fix?",
    "I want to escalate this.",
    "The order status says shipped but I never got it.",
    "This is the third time I am calling about this.",
    "My usage breakdown looks wrong.",
    "The technician never showed up.",
    "Thank you for your patience.",
    "Can you diagnose the problem remotely?",
    "Please diagnose this issue.",
  ],
  lecture: [
    "What is gradient descent?",
    "Can you explain that again more simply?",
    "There are three stages in this process.",
    "What is the difference between mitosis and meiosis?",
    "How does photosynthesis work?",
    "What is the Krebs cycle?",
    "What were the causes of the French Revolution?",
    "What is the chronology of the Roman emperors?",
    "What is the sequence of events leading to World War One?",
    "What are the prerequisites for this course?",
    "Explain the life cycle of a star.",
    "What is a finite automaton?",
    "The DFA accepts strings ending in ab.",
    "So the NFA has three states.",
    "Is this DFA minimal?",
    "How do these concepts relate?",
    "What is the method used in this study?",
    "What is the main contribution of this paper?",
    "What sample size did they use?",
    "The method described in the paper uses a transformer.",
    "What does the graph on this slide show?",
    "Here the function grows by 5 percent each step.",
    "The population growth was 2% per year.",
    "What is the conceptual framework here?",
    "The research pipeline has four steps.",
    "What is the experimental protocol?",
    "What is an entity relationship model?",
    "Chen notation uses diamonds for relationships.",
    "What is a class in UML?",
    "Is UML still used?",
    "This will be on the exam.",
    "What is the timeline of the Cold War?",
    "The heat map on the slide shows attention weights.",
  ],
  smallTalk: [
    "Hi, how are you?",
    "How was your weekend?",
    "Sounds good, thanks.",
    "Can you hear me okay?",
    "Sorry, I was on mute.",
    "Let me share my screen.",
    "Give me a second.",
    "That makes sense.",
    "Great, thank you.",
    "Okay.",
    "Um, so, yeah.",
    "Right, right.",
    "Could you repeat that?",
    "I will show you around the office next week.",
    "Let us put a pin in that.",
    "Let us map out some time next week.",
    "I will sketch something out and get back to you.",
    "Let me paint you a picture of how we work.",
    "Picture this.",
    "We are on the same page.",
    "I see what you mean.",
    "Show me the money.",
    "Give me a break.",
    "Make sense?",
    "Make it quick.",
    "Draw your own conclusions.",
    "That drew a lot of attention.",
    "I would not draw that conclusion.",
    "Let me illustrate with a story.",
    "Can you illustrate that with an example from your experience?",
    "To illustrate, at my last job we cut latency in half.",
    "We went back to the drawing board.",
    "The whiteboard interview is next.",
    "Is there a whiteboard round?",
    "I can not visualise myself in that role.",
    "It is hard to visualize the impact.",
  ],
  statements: [
    "We use a microservices architecture.",
    "Our system has three main components.",
    "The architecture is event driven.",
    "The data flows from the API to the queue.",
    "The request flow goes through the gateway.",
    "We deploy on Kubernetes.",
    "The state machine has five states.",
    "I built a recommendation engine.",
    "I designed the payment system at my last company.",
    "We redesigned the checkout service last year.",
    "The system design round is tomorrow.",
    "System design is my weakest area.",
    "I am preparing for system design interviews.",
    "Our architecture for the data pipeline is batch based.",
    "The high-level design of the service was approved.",
    "The overall architecture of the app is a monolith.",
    "The sequence does not matter.",
    "The process took three weeks.",
    "The algorithm is O(n).",
    "The workflow is fine.",
    "The components are loosely coupled.",
  ],
  garbled: [
    "so um design uh",
    "the the the",
    "and then the the chart uh",
    "diagram",
    "chart",
    "plot",
    "graph",
    "timeline",
    "table",
    "sequence",
    "schema",
    "so like the flow is",
    "yeah the pipeline",
    "right so the life cycle of the",
    "can you",
    "show",
    "show me",
    "uh draw",
    "so the architecture",
    "what about the",
    "instead of",
    "what if",
    "growth",
    "process",
    "how it how does it work",
    "er",
    "er diagram",
    "the er was packed last night",
    "I went to the ER model exhibit",
    "uml",
    "forecast",
    "funnel",
    "gantt",
    "i mean the",
    "mind map",
    "decision tree",
    "state machine",
  ],
  runOn: [
    "So I was working at this company for about three years and during that time we rebuilt the whole checkout service and I led a team of five engineers and we shipped it in six months and then revenue grew by about 20 percent and after that I moved to the platform team where I worked on the data pipeline.",
    "Okay so the question is basically you have an array of integers and you need to find two numbers that add up to a target and return their indices and you can assume there is exactly one solution and you may not use the same element twice so how would you do that.",
    "Yeah so thanks for joining today, what I wanted to cover is first a quick intro then the pricing then we can talk about the rollout plan and timeline and who is involved on your side and then next steps, does that work for everyone.",
    "So in the standup yesterday we talked about the migration and Priya said she is blocked on the schema change and Tom is waiting for the API and I think the release is going to slip by a week unless we cut the reporting feature.",
    "Right so the customer called in saying the bill went up by thirty dollars and they wanted to know why and whether they are eligible for a refund and I told them I would check the usage breakdown and get back to them.",
    "So today we are going to look at how the process works, first the cell takes in glucose, then glycolysis happens, then the Krebs cycle, and finally the electron transport chain, and at each step ATP is produced.",
    "I think the main thing I learned from that project was that you have to plan the rollout carefully and compare the options early and make sure dependencies on other teams are tracked, otherwise you end up blocked.",
  ],
});

export const EXPLICIT = Object.freeze([
  "Can you put that in a table?",
  "Put that in a table.",
  "Can you put this into a table for me?",
  "Make a table comparing the three vendors.",
  "Give me a table of the options.",
  "Show this as a table.",
  "Tabulate the results.",
  "Can you tabulate that?",
  "Visualise this.",
  "Visualize that for me.",
  "Can you visualise the data flow?",
  "Sketch out the architecture.",
  "Sketch it out.",
  "Give me a diagram of the system.",
  "Give me a diagram of how OAuth works.",
  "I want a diagram of this.",
  "I need a diagram.",
  "A diagram would help here.",
  "A diagram please.",
  "Diagram please.",
  "Diagram this.",
  "Diagram it.",
  "Show this graphically.",
  "Show it graphically.",
  "Can you show that visually?",
  "Represent this visually.",
  "Illustrate the process.",
  "Can you illustrate how the cache works?",
  "I would like to see a picture of how these connect.",
  "Can I see a flowchart of the login process?",
  "Flowchart of the login process please.",
  "Flow chart for the onboarding.",
  "So before we go on, can you draw the architecture, I think that would help.",
  "Okay thanks, and could you also organise that into a comparison table?",
  "Can you graph that?",
  "Graph it.",
  "Chart it.",
  "Plot it.",
  "Can you plot that?",
  "Can you chart that for me?",
  "Put it on a chart.",
  "Put it in a chart.",
  "Put this on a timeline.",
  "Lay it out on a timeline.",
  "Make a timeline of the events.",
  "Make a gantt chart of the plan.",
  "Mind map this.",
  "Make a mind map of the topics.",
  "Draw a decision tree for this.",
  "Can you whiteboard this?",
  "Map this out.",
  "Map it out for me.",
  "Depict the flow.",
  "Could you depict that as a state machine?",
  "Show the organisation chart.",
  "Show me an org chart.",
  "Give me a visual.",
  "Can I get a visual of that?",
  "A visual would help.",
  "Show me a picture of the architecture.",
  "Can you do a sequence diagram for the login?",
  "Do a diagram.",
  "I need an ER diagram for a bookstore.",
  "ER diagram for a bookstore.",
  "Class diagram for a parking lot.",
  "Can we see the breakdown as a pie chart?",
  "Bar chart of signups by month please.",
  "Line graph of revenue.",
  "Show a bar graph of the results.",
  "Can you turn that into a diagram?",
  "Turn this into a chart.",
  "Convert that to a table.",
  "Summarise that in a table.",
  "Summarize this as a table.",
  "Tables please, comparing A and B.",
  "I want to see this as a graph.",
  "What would that look like as a diagram?",
  "What does that look like as a flowchart?",
  "Would you draw that for me?",
  "Will you draw it?",
  "Draw it.",
  "Let us see a diagram.",
  "Let me see the diagram.",
  "Pull up a diagram of the request flow.",
  "Could I have a schematic of the system?",
  "Block diagram of the system please.",
  "Compare these three options in a table.",
  "Compare them side by side.",
  "Give me a side-by-side comparison.",
  "Can you make a matrix of features versus vendors?",
  "Venn diagram of the two skill sets.",
  "Show the swimlanes for this process.",
  "Draw a tree of the folder structure.",
  "Can you show the hierarchy?",
  "Show the hierarchy as a tree.",
  "Can you display that as a chart?",
  "Display the data flow.",
  "Present this as a timeline.",
  "Model the data for a blog as an ER diagram.",
  "What is the ER diagram for a library system?",
  "Can you do a quick sketch of the components?",
  "Quick sketch of the architecture?",
  "Roadmap this for me visually.",
  "Could you colour-code that in a table?",
  "Show me the workflow diagram.",
  "Could you organise that into a table?",
  "Let us diagram this out.",
  "I would love a diagram here.",
  "Please include a diagram.",
  "Add a diagram.",
  "With a diagram please.",
  "Explain with a diagram.",
  "Explain with diagrams.",
  "Use a diagram to explain DNS.",
  "Explain DNS using diagrams.",
  "Explain it with a chart.",
  "Explain TCP handshake and include a sequence diagram.",
]);

export const CODING_QUESTIONS = Object.freeze([
  "Design an LRU cache.",
  "Design an LRU cache with O(1) get and put.",
  "Design a circular queue.",
  "Design a queue using two stacks.",
  "Design a hit counter.",
  "Design a search autocomplete system.",
  "Design a leaderboard.",
  "Design Twitter.",
  "Design an in-memory key-value store with transactions.",
  "Design a min stack.",
  "Design a snake game.",
  "Design a browser history.",
  "Design a task scheduler that runs jobs with a cooldown.",
  "Design a rate limiter class with an allow method.",
  "Design a data structure for a time-based key-value store.",
  "Design an elevator controller class.",
  "Design a vending machine.",
  "Design a thread-safe bounded blocking queue.",
  "Design a logger rate limiter.",
  "Design a file system with mkdir and ls.",
  "Design a HashSet without using any built-in hash table libraries.",
  "Design a stack that supports increment operations.",
  "Design a parking system with big, medium and small slots.",
  "How would you design a cache with TTL eviction, code it up.",
  "Given the schema users(id, name) and orders(id, user_id), find users with no orders.",
  "Here is the schema: employees and departments. Find the top earner per department.",
  "Given this table schema, how would you find duplicate emails?",
  "Given a database schema, which index would you add?",
  "Create a decision tree classifier from scratch.",
  "Build a decision tree from this dataset and return the root.",
  "Given prerequisites as pairs, return the order of courses to take.",
  "You have a list of packages and their dependencies, return the install order.",
  "Detect a circular dependency in a list of modules.",
  "Resolve dependencies between build targets.",
  "What does the tree look like after inserting 7?",
  "What will the heap look like after 3 pops?",
  "What would the array look like after 2 rotations?",
  "The array grows by 2 each time it fills, what is the amortised cost of append?",
  "If the input grows by 10x, how does the runtime change?",
  "Growth of 100 percent each resize, analyse the cost.",
  "Simulate a DFA on an input string.",
  "Given a DFA as a transition table, return whether it accepts the string.",
  "Convert an NFA to a DFA.",
  "Write a regex matcher using an NFA.",
  "Implement an automaton that matches a*b.",
  "Count the strings of length n accepted by this automaton.",
  "Write an algorithm to detect the lifecycle state of an order.",
  "Track the lifecycle of objects in a pool.",
  "Compare the complexity of quicksort and mergesort.",
  "Compare the trade-offs between BFS and DFS here.",
  "Compare the costs of the two approaches.",
  "Make a tree from this list of parent-child pairs.",
  "Turn this sorted array into a balanced tree.",
  "Convert the adjacency matrix into an adjacency list.",
  "Build a graph of the dependencies and find cycles.",
  "Build the graph showing which nodes are reachable.",
  "Generate a heat map of visit counts on the grid.",
  "Plot twist: now do it in O(1) space.",
  "Model the elevator as a state machine.",
  "Model the vending machine states.",
  "Model the entities for a library system.",
  "Model the tables for a food delivery app.",
  "How would you model users and their friends?",
  "Design the classes for a chess game.",
  "Design the objects for an elevator.",
  "What classes for a deck of cards would you write?",
  "Write the classes and objects for a parking lot.",
  "Show me the inheritance hierarchy you would use.",
  "Walk me through the algorithm step by step.",
  "Visualize the algorithm.",
  "Show the sequence of calls in your recursion.",
  "Give me the sequence that the generator produces.",
  "Show the state transitions of your DP.",
  "Print the matrix in spiral order.",
  "Create a table of prefix sums.",
  "Build a table of dp values bottom up.",
  "Make a table dp[i][j] and fill it.",
  "Put the results in a table and return it.",
  "Given the UML below, implement the classes.",
  "Find the funnel conversion rate between two events in SQL.",
  "Given a timeline of events, find the longest gap.",
  "Merge the two timelines of events.",
  "Compute the break-even point given a list of costs and revenues.",
  "Compute the projected growth after n periods.",
  "Write a query for the cost breakdown per department.",
  "What is the process for inserting into a red-black tree?",
  "Explain the workflow of your algorithm.",
  "Which task blocks which in this DAG?",
  "Implement topological sort for the prerequisites graph.",
  "Add a function that plots the results.",
  "Use matplotlib to make a bar chart of the counts.",
  "Draw a triangle of stars with nested loops.",
  "Draw the output on the canvas using the 2D context.",
  "Implement flood fill, like the paint bucket when you draw.",
  "Sketch the recursion in pseudocode.",
  "How do you handle the hand-off between the producer and consumer threads?",
  "Who handles the lock in this code?",
  "What is blocking the event loop here?",
]);

export const UNRELATED_FOLLOW_UPS = Object.freeze([
  "What's your notice period?",
  "Can you add me on LinkedIn?",
  "How do we increase retention?",
  "Let's move on to pricing.",
  "Set up a meeting for Tuesday.",
  "What are your salary expectations?",
  "Make sure you send me your resume.",
  "Use the bathroom down the hall.",
  "Can you make it on Friday?",
  "Add me to the invite.",
  "Put me down for Thursday.",
  "Change of topic, how do you handle conflict?",
  "Try again later.",
  "Move on.",
  "Okay, next question.",
  "Tell me about your last job instead of this one.",
  "What if we had lunch first?",
  "How would it work with your visa?",
  "How does this work with your schedule?",
  "How do we handle the offer?",
  "How can we support you during onboarding?",
  "Is that okay?",
  "Does that make sense?",
  "Why is this taking so long?",
  "What time is it?",
  "Is this your first interview with us?",
  "Can you hear me, is this working?",
  "Do you want to take a break here?",
  "Who is the provider for your health insurance?",
  "Where do you see yourself as a worker in five years?",
  "How was the delivery of your last project?",
  "What notification settings do you use on Slack?",
  "I got an email about that.",
  "What is your email?",
  "Send me an SMS when you arrive.",
  "Did you log your hours?",
  "What about 3 months of notice?",
  "What if I told you the salary is 20% higher?",
  "Shorter hours would be nice.",
  "Can you say that again?",
  "Tell me about yourself in a shorter form.",
  "I want something more casual for Friday.",
  "Make it more fun.",
  "Just show me your side of the story.",
  "Give me a part of your day you enjoy.",
  "Show me the money.",
  "Just a second, let me check the flow of the agenda.",
  "Reverse a linked list.",
  "Write a function to merge two sorted arrays.",
  "Thanks, that was great.",
  "Okay.",
  "Right.",
  "So, anyway.",
  "Instead of Monday, can we do Tuesday?",
  "Remove me from the mailing list.",
  "Support for parents is great here.",
  "Scale of one to ten, how confident are you?",
  "Mark, can you take notes?",
  "Set expectations with the client.",
  "Handle with care.",
  "Drop me a line.",
  "Split the bill?",
  "Assume I am five years old and explain recursion.",
  "Lower your voice please.",
  "Raise your hand if you agree.",
]);
