// electron/llm/visionTestGlyphs.ts
//
// GENERATED by scripts/generate-vision-test-glyphs.py — do not edit by hand.
//
// The digits 0-9 of Inter Bold at 150 px, as 1-bit bitmaps: ten cells of
// GLYPH_W x GLYPH_H pixels, rows padded to a byte, most significant bit first,
// zlib-deflated and base64-encoded. Inter is (c) The Inter Project Authors,
// SIL Open Font License 1.1 (src/font/Inter-4.1/LICENSE.txt).

export const GLYPH_W = 101;
export const GLYPH_H = 114;
export const GLYPHS_DEFLATED_BASE64 = [
  'eNrtm0+O5CYUxkEsvOQIHIUcJcfIIpIt5QA5wlzF0iyyzBFClAOE7IhkmVQZeHwPQ42rejLRTLo23b/uKozxe9/7AyVE+9Jxod9l',
  'jBuBiTGuBeYb+Pqu+r7pDhE+Qh+yB7j6+TLC8fkygkqww2B5OJ1hQVjrZTLYDK5eJl+oQLjD/ZffMsjjZ56CPD5rEqjjejrNRx0z',
  'mRKkHzJNbjrenUGnQdNMdbr2fIBJYI+ZmjRFglWUH5bAEegCSwf8cYG8YFdAHZBXWR3zfQ5khq0HG9nNO/RAPAK2vM8/n/qAw2Wj',
  'YIY0MDHXmCUz2NaUKzDzZ47BXIY5E7lZbB1QHj5uKpDTitj6NgGTACYOpgfrSWqYCDF5YsIl4JqN2DEZZALJpJOJKpdbJsRMol97',
  'lXsrcyCYEDSCRZgRIoBCmBAMgkWYAWQEUAgawSDMr8EHgN0AbAgewSGsCAJgRwgIHmFFWBAEwI8IPyB8j/AdgniHd3iHrwGuvSx8',
  'YsJQgKIsI4SPCQOLwZBjMRhBACzRLGCc2zAN31kaLjBqLhhcFwy7K4LD6OzrNSt4laeQAv9MsAvIybdjGluaWih/yumMTDNNSQsD',
  'QbAm1e/AIkp2lJ+TfQsIgrr6Q9grzNeAZQUIsoFAoBrwaFgeUoySvFDKVye99mFGw45wbzLCpBUCM2aNUzM4G4sTmBEwSVJtIoMj',
  '7zgyc6CAI3sc2WGK9KUvc8rEcOQdR95w5IAjexzZfZkbYJchQdDfMjzxMuAvqlnt+i9UclWlt0mCmZJ3GipvV/KzeLNqqqvk1FCR',
  'oORrsdNU3FXx3lC8A0lF1qK+eLuzeMcKtsDSBzP8zwWJ/ox6zSSaqfKEoEc6CGKhzkVTz3gU5gTqZGMrAjqxHwIv+/zwOmw6fNYO',
  'wSMEvBJTol10dVE1MYdHowXlaxDBzDDq6Ufg+zB9AnITRn8Ceu0Z00Btz9gCjkKlKc6UIZDxpEiSHDSvpa765kqZP5HYiQZI43eU',
  'AAbbCx2ZcxPmQd8FlY/3XZhanlstrhsDmUS/9ho3UcwQ7PO9FgZy2IUZt2QY6GGz5lrnhkMc9XTGDR4Gt6n9ia2fXxF+xj7QzxgP',
  'NcCuscGDsFWIAPc8GcETKITb1BzCSqAR7nGmD/cwArBXmBHu1goQCCTCkcJ34T5PhJVAI5jcYC1AQTGFO0313D6AUo4tVGr0IJUa',
  'FRzBhKCLFC0UnTWp3PIorlPtxgq5rUIEIHW6S8o3DdW7F/H/g7e8bC9M/dsw/zcQMGENmLCOwX9xkA24t4PZKqiSCsqk8IHAlgTh',
  'DpiTfKRs4wa/UIajjoCV0w2VNpppl64WXQprSIIVwQ3BIwRMzAp4Gam0ipQ4p722uqMWaEv79kdHu3C396/Yxlk6WfSCvjIA0+TX',
  'Kzrq0zB9Vuhcx2AY6oFpYMG90Aq2RCuH258Oi1VPy9uWvhv1BqaSk++9QtpLqLdZ8d2v0Xkpb3tHKBaEc8uANRNYm4G1knlrgrWf',
  'WWOaNTqOD2GXbcOc/JKmS1QONENWuWqcgcVq91yeety0DVhWbHhzEUsRStnqcBIXXuIjUQgTlkkaCygGBqP7sWplCjYnjZHadKXZ',
  'dxS9pShOP2YCqoOzDRJsZPG5Q5GMmEGubKcuOEzw3DV3f2VH5X6Vml1TELsDtQVy3k3HhI6lKyFY0OreMnIJq7vXDsYtt5zoAaea',
  'IlI7yiBYeqY3mOmZEmwJ6mOcMWM74I981fl4u6ngS305R3imc3pDur2ZxkmwUWMgd4gNgi7gW6A+hWtBFVgJ7CNYKHxbLA4ugsEB',
  'eqAKrFhqjKHej0YbnXANGChcN0UrujYg8SmkJwM+t5I3xlyoFT/dy/MjVd4RmNczPQgoG0xDHKoLE6EFtQr1ekdJY2LnO/07gbJ+',
  'jLBhA8R3t4Ju/3Kvp+Tf9C5Cb0thbkD0IfIm8z7cB9yG+4DhQtty3AQdZ3njzPD9dto7uLIfMA3bzeMtWzNseNtrxhZHtyPfb+fF',
  '2/nK3eWZHc8HZ1fW4dmV/eLZFY91ScCKZcOQsYtTYfM5jqtsim1y1uMqkfbPU3E9XdvxrMdV/HDH07U7nv3tz9dhb2HCMzItOOqz',
  'qrJPu9WjJQiS6tNQje54w1SL1Wpnh//aWqw6gcXqh/abAMNiNZzNhRuSPp3IDbh1EpglLudqt2d8D+zt0yYWVG/rfMKtc41dAk17',
  'egJ3+6puJim02Jqw1DtfSSpNAYElgsCqoAL1jB6AfxXiYzD5OrD9OdP9OKpLCBwVQ5ZWZy2HWiTBRlt3pngw3wvFFHTHltuOzbit',
  '7cz1OzLupDum9w2Xs6RJZsrz+aT5Mmq1uO5Bn9utX9rxtCyNh5hhIaBKvM508p+dKTlzphVvruNZGtfAoJvZT8r6ggu/4iNx7fNR',
  'xQFzAVxlfSpGEWgFJ/LGegpRo5IbPLtCEGvYn0v3Zem45kJnTswZqp+udMxEPwL3VvDPgsHTDB2wVPN6vO0KMzYT5lLkOzrdZspa',
  '5y5ByM+vCOREkHreududAksBVzT/MDebDaEeX/NkIX+TerTwF33R5fb6nb7nlfo4ngz2I/UUbq+fqo3FqKCjvymQiqCgeesUnJRY',
  'CxwpRoFjm2YqMEVRQYgzPN2C77Th6mNk1ivwMdZPzmj+5Bhr4zISnUmhm03kgBt5I+1wVKdFd9a9nRSJeiBiTymYhqC6sPDOEk2W',
  'BbDklJ2yZjksaiLLewPqKPu65do9DsXydWHzP/4BUw4zlw==',
].join('');
