#!/usr/bin/env python3
"""Regenerate electron/llm/visionTestGlyphs.ts (development-time only).

The one-time vision test (electron/llm/visionTestImage.ts) shows a model a
four-digit number. Real models misread hand-made block fonts, so the digits are
rasterised ONCE, here, from the repo's own Inter Bold (SIL Open Font License,
src/font/Inter-4.1/LICENSE.txt), and embedded as 1-bit bitmaps. The app never
runs this script and never touches a font at runtime: it is not referenced by
package.json and needs Pillow (`pip install pillow`).

    python3 scripts/generate-vision-test-glyphs.py
"""
import base64, os, zlib
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = os.path.join(ROOT, 'src/font/Inter-4.1/extras/otf/Inter-Bold.otf')
OUT = os.path.join(ROOT, 'electron/llm/visionTestGlyphs.ts')
SIZE = 150

font = ImageFont.truetype(FONT, SIZE)
boxes = [font.getbbox(str(d)) for d in range(10)]
top = min(b[1] for b in boxes); bottom = max(b[3] for b in boxes)
width = max(b[2] - b[0] for b in boxes); height = bottom - top
row_bytes = (width + 7) // 8
bits = bytearray()
for d, box in enumerate(boxes):
    cell = Image.new('L', (width, height), 255)
    x = (width - (box[2] - box[0])) // 2 - box[0]
    ImageDraw.Draw(cell).text((x, -top), str(d), fill=0, font=font)
    px = cell.load()
    for y in range(height):
        row = bytearray(row_bytes)
        for cx in range(width):
            if px[cx, y] < 128:
                row[cx >> 3] |= 0x80 >> (cx & 7)
        bits += row
packed = base64.b64encode(zlib.compress(bytes(bits), 9)).decode('ascii')
lines = '\n'.join(f"  '{packed[i:i + 100]}'," for i in range(0, len(packed), 100))
with open(OUT, 'w', newline='\n') as f:
    f.write(f"""// electron/llm/visionTestGlyphs.ts
//
// GENERATED by scripts/generate-vision-test-glyphs.py — do not edit by hand.
//
// The digits 0-9 of Inter Bold at {SIZE} px, as 1-bit bitmaps: ten cells of
// GLYPH_W x GLYPH_H pixels, rows padded to a byte, most significant bit first,
// zlib-deflated and base64-encoded. Inter is (c) The Inter Project Authors,
// SIL Open Font License 1.1 (src/font/Inter-4.1/LICENSE.txt).

export const GLYPH_W = {width};
export const GLYPH_H = {height};
export const GLYPHS_DEFLATED_BASE64 = [
{lines}
].join('');
""")
print(f'wrote {OUT}: {width}x{height} per digit, {len(packed)} base64 chars')
